<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfee5f27f35c3b877f9ce72b03bd281d4
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Medoo\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Medoo\\' => 
        array (
            0 => __DIR__ . '/..' . '/catfan/medoo/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfee5f27f35c3b877f9ce72b03bd281d4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfee5f27f35c3b877f9ce72b03bd281d4::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
